### ISSUE TITLE
تانل ws

### ISSUE THREAD

**Issue by generalcyberi** [hiddify/hiddify-relay#13]
سلام توضیحاتی برای تانل ws که جدید اضافه کردید بزایرد ممنون

**Comment by H-Return** [comment]
دورد وقتتون بخیر.
همون روش تانل ws هستش که میتونید [اینجا](https://github.com/hiddify/Hiddify-Manager/discussions/851) درموردش مطالعه کنید.

**Comment by lymanjre** [comment]
مقاله مربوط به راهنمای این اپ در [اینجا](https://hiddify.com/fa/manager/domain-worker-cdn-and-tunneling/How-to-setup-relay-server-using-Hiddify-Relay-Builder/) قابل دسترس است
