### ISSUE TITLE
باگ برای اخرین اپدیت

### ISSUE THREAD

**Issue by Amirwixa** [hiddify/hiddify-relay#23]
سلام خسته نباشید
آخرین آپدیت مشکل پیدا کرده با سرور های آروان و تانل نمیشه 
سی دی ان ها عوض شد 
سرور کاملا اوکی بود
ولی تانل فعال نمیشه هیچکدوم از تانل ها 
لطفا بررسی کنید

**Comment by Amirwixa** [comment]
یه سرور آروان میخوای بدم چک کنی ؟
نمیدونم چه اطلاعاتی لازم داری
اسکریپت که ران میشه  کلا با دانلود و نصب همه ی پروکسی ها مشکل داره و تا نصفه میره استاپ میزنه 
اگه میدونی سرور ایران بدمت 
@niold تلگرام

**Comment by H-Return** [comment]
سلام خیر نیازی نیست
بررسی شد مشکل از IPv6 سرور های ایران هستش
بدون IPv6 چک کنید
