### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by rnj79** [hiddify/hiddify-relay#5]
برای آیپی ورژن 6 هم اضاف کنید راهی

**Comment by HiddifySupport-Return** [comment]
سلام.
میتونید dokodemo-door استفاده کنید و ساب دامنه با IP ورژن 6 بدید.
موفق باشید.

**Comment by HiddifySupport-Return** [comment]
> برای آیپی ورژن 6 هم اضاف کنید راهی

سلام.
میتونید dokodemo-door استفاده کنید و ساب دامنه با IP ورژن 6 بدید.
موفق باشید.
